### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by Carl-Hossler** [wattsight/wapi-python#48]
Hi,

I am getting the following error:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='auth.wattsight.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))`

Here is my code:
`import wapi
import pandas as pd`

`session = wapi.Session(config_file='config.ini')`
`start_date = pd.Timestamp('2019-1-1 00:00')`
`end_date = pd.Timestamp('2019-3-31 23:00')`
`curve_name = 'con fr mwh/h cet min15 a'`
`curve = session.get_curve(name=curve_name)`
`ts = curve.get_data(data_from=start_date, data_to=end_date)`
`s = ts.to_pandas()`

and the packages installed in my virtual environment:

Name | Version | Build | Channel
------------ | ------------- | ------------- | -------------
asn1crypto     |           0.24.0      |             pypi_0  |  pypi
asn1crypto     |          0.24.0        |           pypi_0  |  pypi
certifi          |         2019.3.9       |          py36_0 |   anaconda
cffi              |        1.12.3          |         pypi_0 |   pypi
chardet             |      3.0.4       |             pypi_0  |  pypi
cryptography      |        2.6.1       |             pypi_0  |  pypi
future            |        0.17.1     |             pypi_0 |   pypi
idna                      2.8           |           pypi_0  |  pypi
ndg-httpsclient     |      0.5.1     |               pypi_0  |  pypi
numpy             |        1.16.3      |             pypi_0 |   pypi
pandas          |          0.24.2       |            pypi_0 |   pypi
pip            |           19.1         |            py36_0  |  anaconda
pyasn1       |             0.4.5      |              pypi_0   | pypi
pycparser      |           2.19        |             pypi_0  |  pypi
pyopenssl      |           19.0.0     |              pypi_0 |  pypi
python         |           3.6.8         |       h9f7ef89_7 |   anaconda
python-dateutil      |     2.8.0      |              pypi_0  |  pypi
pytz           |           2019.1      |             pypi_0 |   pypi
requests        |          2.21.0      |             pypi_0  |  pypi
setuptools     |           41.0.1     |             py36_0  |  anaconda
six             |          1.12.0        |           pypi_0 |   pypi
sqlite           |         3.28.0       |        he774522_0  |  anaconda
sseclient     |            0.0.24       |            pypi_0 |  pypi
urllib3         |          1.24.2        |           pypi_0  |  pypi
vc               |         14.1      |           h0510ff6_4  |  anaconda
vs2015_runtime     |       14.15.26706    |     h3a45250_4  |  anaconda
wapi-python      |         0.3.1        |            pypi_0 |   pypi
wheel              |       0.33.1        |           py36_0  |  anaconda
wincertstore          |    0.2        |      py36h7fe50ca_0  | anaconda

**Comment by haraldnh** [comment]
Every report we have seen of this (and similar) errors have so far been an issue with your proxy server which tries to sniff the https traffic.  The requests library treats this as an attempted MITM attack and notifies you of the broken chain of trust.

There are basically two ways to handle this: The preferred way is to ask your IT people to not break https integrity.  The other way is to replace the CA bundle used by the requests package with your locally tailored version.

There are no way we can handle this in wapi-python without breaking the integrity for everybody else, sorry.
