### ISSUE TITLE
Please clarify time zones in the docs

### ISSUE THREAD

**Issue by cdeil** [wattsight/wapi-python#70]
Thanks for making this package!

Could you please clarify time zones in the docs?

Specifically, we are calling [Session.get_curve](https://wapi-python.readthedocs.io/en/latest/modules.html#wapi.session.Session.get_curve) and [TimeSeriesCurve.get_data](https://wapi-python.readthedocs.io/en/latest/modules.html#wapi.curves.TimeSeriesCurve.get_data) for this case:
```
    curve = session.get_curve(name="pri de spot €/mwh cet h a")
```
and we're wondering how summer time (CET vs CEST) is handled and how the "time_zone" and "output_time_zone" are taken into account.

We'll look at the code and figure it out now, but I think it would be great for all users if you could improve the docs wrt. how time zones work exactly.

Current docstring for "get_data" is this:
 
![Screenshot 2020-06-18 at 10 19 08](https://user-images.githubusercontent.com/852409/84996138-2afc5700-b14d-11ea-8a63-985b6fd0c3c1.png)

Current search result for "zone" is this (it's similar for "timezone" or "time zone"):
![Screenshot 2020-06-18 at 10 21 32](https://user-images.githubusercontent.com/852409/84996511-a8c06280-b14d-11ea-8312-463787f0b400.png)

**Comment by stila** [comment]
Thanks for reaching out. Our official documentation is here:
https://wattsight-wapi-python.readthedocs-hosted.com/en/latest/quickstart.html

Both `time_zone` and `output_time_zone` are documented there. All curves are CET, and returned with the correct `tzoffset`. We have gotten some feedback on these two arguments previously and will look into making it less confusing in the future.
