### ISSUE TITLE
Delete https://wapi-python.readthedocs.io ?

### ISSUE THREAD

**Issue by cdeil** [wattsight/wapi-python#71]
Google pointed me to https://wapi-python.readthedocs.io

Now in https://github.com/wattsight/wapi-python/issues/70#issuecomment-645896473 by @stila I see that this documentation is very outdated (from 2018), and the current documentation is at https://wattsight-wapi-python.readthedocs-hosted.com/ .

Suggest to delete the old outdated docs on readthedocs.io to avoid this confusion.

**Comment by stila** [comment]
I have already reached out to the maintainer to delete it - so hopefully this should not be an issue anymore very soon. 🙂

**Comment by stila** [comment]
It's deleted now. Thanks for letting us know!

**Comment by cdeil** [comment]
![You are fast!](https://media.giphy.com/media/3o7ZetIsjtbkgNE1I4/giphy.gif)
