### ISSUE TITLE
MissingSchema: Invalid URL

### ISSUE THREAD

**Issue by raikb** [wattsight/wapi-python#76]
Hi!
When I try to follow you example (https://github.com/wattsight/wapi-python/blob/master/examples/Timeseries_curve_examples/ts_simple_read.py), I get the following error:
`MissingSchema: Invalid URL '/api/curves/get?name=tt+de+con+%C2%B0c+cet+min15+s': No schema supplied. Perhaps you meant http:///api/curves/get?name=tt+de+con+%C2%B0c+cet+min15+s?`

I created a specific environment with conda to eliminate this as an error source:
`conda create -n wapi python=3.6 anaconda`
And the I run:
`pip install -U wapi-python`

This is my code:
import pandas as pd
import wapi
session = wapi.Session('config.ini')
start_date = pd.Timestamp('2018-6-1 00:00')
end_date =  pd.Timestamp('2018-6-8 00:00')
curve_name = 'tt de con °c cet min15 s'
curve = session.get_curve(name=curve_name)

Any idea what is wrong? Thanks!

**Comment by raikb** [comment]
I tried the same code on a machine outside of the company network to check whether it is a proxy issue but I get the same error message.

**Comment by rune-bk** [comment]
Hi @raikb, 

I suspect you may be missing `urlbase` in your config file as seen here:
https://github.com/wattsight/wapi-python/blob/master/sampleconfig.ini

Let me know how it goes.
We also usually reply a bit faster on support@wattsight.com for future support questions.

**Comment by raikb** [comment]
This is the content of my config file without the secret parameters of course:
`[common]
urlbase = https://api.wattsight.com
auth_type = OAuth
timeout = 300

[OAuth]
id = 
secret = 
auth_urlbase = https://auth.wattsight.com`

So it must be something else. Anything else I could check?

**Comment by raikb** [comment]
What is interesting is that I get the following error if I switch from https in the base url to http:
`MissingSchema: Invalid URL '/api/curves/get?name=tt+de+con+%C2%B0c+cet+min15+s': No schema supplied. Perhaps you meant http:///api/curves/get?name=tt+de+con+%C2%B0c+cet+min15+s?`
So the recommended URL is adjusted based on what I define in the config file.

**Comment by rune-bk** [comment]
Try removing the urlbase line entirely. We should have a default in place.

**Comment by raikb** [comment]
I still get this error:
`MissingSchema: Invalid URL '/api/curves/get?name=tt+de+con+%C2%B0c+cet+min15+s': No schema supplied. Perhaps you meant http:///api/curves/get?name=tt+de+con+%C2%B0c+cet+min15+s?`
However, I think I found the problem. In the code from above I used:
`session = wapi.Session('config.ini')`
The Session class interprets "config.ini" as the urlbase parameter because this is the first one in line. So all I need to fix this is:
`session = wapi.Session(config_file='config.ini')`
Quite obvious now.
Now I get this error:
`SSLError: HTTPSConnectionPool(host='auth.wattsight.com', port=443): Max retries exceeded with url: /oauth2/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))`
This might be a proxy problem. I will have a look.
@rune-bk: Thanks for the help so far.

**Comment by rune-bk** [comment]
Oh right I missed that. That makes sense.

Yea that looks very much like a proxy problem. You are missing an env.
See https://requests.readthedocs.io/en/master/user/advanced/#proxies on how to set it.
