### ISSUE TITLE
print curve -> 'ascii' codec can't encode character: ordinal not in range(128)

### ISSUE THREAD

**Issue by gbm** [wattsight/wapi-python#80]
https://github.com/wattsight/wapi-python/blob/dc0d3534b4c8fe0bcc577ac25d93ebeffdfd2dc0/wapi/curves.py#L30

In py2.7 I am getting this error:

`'ascii' codec can't encode character u'\REDACTED' in position REDACTED: ordinal not in range(128)`

when I try 
`print (curve)`

**Comment by rune-bk** [comment]
Hi! This is usually a result of the euro symbol which is part of many of our units and the curve name which is returned when you print the curve like that. 

Ensure your script is in UTF8 and it should work. 

Another note is that we will end support on Python 2.7 soon as 2.7 has reached end of and is no longer officially patched or supported. Old versions of wapi python should work but will not be updated with any api changes. 

If you are making something new I strongly recommend that you use python 3. 

Best regards, 
Rune

**Comment by haraldnh** [comment]
Just to clarify:  Working with python 2.7 and curves that are named with utf-8 names does not work, has not worked in the past and is not high on our list of priorities to fix.

Please do yourself a service and use python 3.x if anything you do involves unicode values.

If you really need this to work, you probably need to modify a lot of the code to both be explicit on converting to/from utf-8, as well as ensuring you never call the wrong function with a plain python 2.7 string as an argument.  It sounds like far more work than I think it is worth, but if you create a pull request we will of course consider it.

On the other hand (as we have stated) python 2.7 support will be dropped quite soon.  It blocks the possibility of adding type hints, async support, etc.

**Comment by gbm** [comment]
Thanks - as I understand your reply, this means that wapi-python 0.7.1 does not fully support python 2.7.
